### ISSUE TITLE
handle `export ... from ...` imports

### ISSUE THREAD

**Issue by bendlas** [egoist/konan#4]
As part of our usage of konan in clojurescript, we tripped over this issue when trying to process `material-components-web`, e.g. with https://unpkg.com/@material/drawer@0.5.4/index.js

Issue on the cljs tracker: https://dev.clojure.org/jira/browse/CLJS-2325

**Comment by egoist** [comment]
Added in `1.2.0`

**Comment by bendlas** [comment]
Great! Thanks for the quick response. It seems, that your patch still doesn't handle `export default`.
https://github.com/tc39/proposal-export-default-from#exporting-a-default-as-default

**Comment by egoist** [comment]
```js
// handled, it's ExportNamedDeclaration
export default from "mod"

// handled, there's `import`
import default from "mod";
export { default };
```
